# remote_theme: "pages-themes/cayman@v0.2.0"
# plugins:
#   - jekyll-remote-theme # Allows the use of remote themes
# # remote_theme: pages-themes/cayman@v0.2.0
# theme: jekyll-theme-cayman

# # Site metadata
# author:
#   name: "Shreya Saxena, John Lafferty"
#   email: "shreya.saxena@yale.edu, john.lafferty@yale.edu" 

header: 
  image: /assets/images/IMG_1523_Original.jpg

title: WTI Neuro-AI Journal Club
description: Welcome to the Spring Semester Series of our Journal Club

remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# show_downloads: false
# google_analytics:
# theme: jekyll-theme-cayman

# title: " Neuro-AI Journal Club"
# description: "Exploring ideas, one paper at a time."

# Optional social links (update or remove as needed)
# social_links:
#   - name: "GitHub"
#     url: "https://github.com/your-organization"
#   - name: "Twitter"
#     url: "https://twitter.com/example"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
defaults:
  # _posts
  - scope:
      path: ""
      type: single
    # values:
    #   show_date: true
