plugins:
  - jekyll-remote-theme # Allows the use of remote themes
remote_theme: "pages-themes/cayman@v0.2.0"
# remote_theme: pages-themes/cayman@v0.2.0


# Site metadata
author:
  name: "Shreya Saxena, John Lafferty"
  email: "shreya.saxena@yale.edu, john.lafferty@yale.edu" 

# title: " Neuro-AI Journal Club"
# description: "Exploring ideas, one paper at a time."

# Optional social links (update or remove as needed)
# social_links:
#   - name: "GitHub"
#     url: "https://github.com/your-organization"
#   - name: "Twitter"
#     url: "https://twitter.com/example"
